[project]
name = "kidz2learn"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "audioop-lts>=0.2.2",
    "phonemizer>=3.3.0",
    "pip>=25.3",
    "pydub>=0.25.1",
    "pyphen>=0.18.1",
    "readchar>=4.2.1",
    "simpleaudio>=1.0.4",
    "sounddevice>=0.5.5",
    "soundfile>=0.13.1",
    "spacy>=3.8.11",
]
