using System.Diagnostics;
using System.Text.Json;
using Kidz2Learn.Model;
using Xunit;

namespace Kidz2Learn.Tests;

/// <summary>
///     Regression test for wwwroot/data/silben-hammer-words.json itself (generated by
///     WaveSplit/GenerateSilbenHammerWords.py) - deserializes it exactly like
///     <see cref="SilbenHammerWordCatalog" /> does at runtime, so a future regeneration that
///     breaks the schema (wrong casing, non-string enum, empty output) fails here instead of
///     silently leaving the in-app catalog empty.
/// </summary>
public class SilbenHammerWordCatalogJsonTests
{
    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        PropertyNameCaseInsensitive = true
    };

    private static string FindRepoRoot()
    {
        var dir = new DirectoryInfo(AppContext.BaseDirectory);
        while (dir is not null && !File.Exists(Path.Combine(dir.FullName, "Kidz2Learn.csproj")))
            dir = dir.Parent;

        return dir?.FullName
            ?? throw new InvalidOperationException("Could not locate repo root from " + AppContext.BaseDirectory);
    }

    [Fact]
    public void GeneratedCatalog_DeserializesToNonEmptyEntriesOfBothTiers()
    {
        var path = Path.Combine(FindRepoRoot(), "wwwroot", "data", "silben-hammer-words.json");
        var json = File.ReadAllText(path);

        var entries = JsonSerializer.Deserialize<List<SilbenHammerWordEntry>>(json, JsonOptions);

        Assert.NotNull(entries);
        Assert.True(entries!.Count > 1000, $"Expected a sizeable catalog, got {entries.Count}");
        Assert.All(entries, e =>
        {
            Assert.False(string.IsNullOrWhiteSpace(e.Word));
            Assert.NotEmpty(e.Syllables);
            Assert.All(e.Syllables, s => Assert.False(string.IsNullOrWhiteSpace(s)));
        });
        Assert.Contains(entries, e => e.Tier == WordTier.Grundschule);
        Assert.Contains(entries, e => e.Tier == WordTier.Schlaukopf);
    }

    [Fact]
    public void SyllableIndex_BuildsFromTheRealCatalogWithinABudget()
    {
        // Regression guard for the "Lade Wort takes 2-3 seconds" bug: SilbenHammerSyllableIndex
        // used to dedupe each pool entry via List.Contains (O(n) per insertion) and was rebuilt on
        // every Silbenhammer burst - quadratic in a common syllable's word count, on ~6000 words,
        // several times a minute. 5s is a very generous ceiling (should be well under 100ms) so
        // this only fails if the O(n^2) shape (or the per-burst rebuild) comes back, not on a
        // merely slow CI box.
        var path = Path.Combine(FindRepoRoot(), "wwwroot", "data", "silben-hammer-words.json");
        var entries = JsonSerializer.Deserialize<List<SilbenHammerWordEntry>>(File.ReadAllText(path), JsonOptions)!;

        var sw = Stopwatch.StartNew();
        var index = SilbenHammerSyllableIndex.Build(entries);
        sw.Stop();

        Assert.True(sw.ElapsedMilliseconds < 5000,
            $"Building the syllable index took {sw.ElapsedMilliseconds}ms - expected well under 5000ms");
        Assert.NotEmpty(index.FirstSyllablePool);
    }
}
